backend:
  name: github
  repo: NuevoFoundation/workshops

publish_mode: editorial_workflow
media_folder: 'static/images/'

collections:
  - name: 'faq' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'FAQ' # Used in the UI
    folder: 'content/faq'
    format: yml
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Question', name: 'title', widget: 'string' }
      - { label: 'Answer', name: 'body', widget: 'markdown' }