backend:
  name: github
  repo: NuevoFoundation/workshops

publish_mode: editorial_workflow
media_folder: 'static/images/'

collections:
  - name: "workshop"
    label: "Workshops"
    label_singular: "Workshop"
    folder: "/content/{{slug}}"
    preview_path: "{{slug}}"
    create: true
    fields:
      - {label: "Slug", name: "slug", widget: "string", hint: "Short name used for the workshop url, ex: 'csharp' "}
      - {label: "Title", name: "title", widget: "string", hint: "Workshop title" }
      - {label: "Description (for blog list)", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "PreReq", name: "prereq", widget: "string", hint:"pre-requisite for this workshop"}
      - {label: "Difficulty", name: "difficulty", widget: 'select', options: ['Beginner', 'Intermediate', 'Advanced'], hint:"Select the difficulty for the workshop"}
      - {label: "Download", name: "download", widget: "string", required: false, hint:"URL to GitHub folder"}
      - {label: "Body", name: "body", widget: "markdown"}  
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "/content/blog"
    preview_path: "blog/{{year}}/{{month}}/{{title}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'faq' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Neuvo Foundation FAQ' # Used in the UI
    folder: 'content/faq'
    create: true # Allow users to create new documents in this collection
    format: yml
    fields:
      - {label: Title, name: title, widget: string, hint: 'Page Title'}
      - label: 'All Questions'
        label_singular: 'Q+A'
        name: 'items'
        widget: 'list'
        fields: 
          - { label: 'Question', name: 'question', widget: 'string', hint: 'Question goes here'}
          - { label: 'Answer', name: 'answer', widget: 'markdown', hint: 'Markdown response to question' }

